# This workflow deploys the static site to GitHub Pages
#
# It triggers on pushes to the main branch.
#
# It uses the actions/deploy-pages action to handle the deployment.

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your site needs to be built, add a build step here.
      # For example:
      # - name: Build
      #   run: |
      #     echo "Building the site..."
      #     # Replace with your build commands
      #     # For example: npm install && npm run build
      #     echo "Build complete."

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository.  If you have a build step,
          # upload the output directory instead.
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4